---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: \.vscode.*/
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.8.0
    hooks:
      - id: eslint
        types: [file]
        files: \.js$
        args: [--fix]
        additional_dependencies:
          - eslint-config-prettier@6.10.0
          - eslint-plugin-prettier@3.1.2

  - repo: https://github.com/prettier/prettier
    rev: '1.19.1'
    hooks:
      - id: prettier
